import { formatarData, formatarFormato, formatarPorcentagem } from "@/biblioteca/formatacao";
import { EstruturaAutenticada } from "@/componentes/estrutura-autenticada";
import { formatarMetodoEstudo } from "@/dominio/sessoes/metodos";
import { exigirUsuario } from "@/servidor/autenticacao";
import { listarHistoricoDeAtividadesPessoal } from "@/servidor/sessoes";

export default async function PaginaHistorico() {
  const usuario = await exigirUsuario();
  const atividades = await listarHistoricoDeAtividadesPessoal(usuario.id);
  return <EstruturaAutenticada usuarioNome={usuario.nome}><main className="pagina" id="conteudo-principal" tabIndex={-1}>
    <header className="cabecalho"><div><p className="marca">LABORATÓRIO PESSOAL DE APRENDIZAGEM</p><h1>Histórico de atividades</h1><p className="rotulo">Sessões e avaliações da sua conta, em ordem cronológica e com o contexto de origem.</p></div></header>
    <div className="aviso"><strong>Como interpretar.</strong> Sessões inválidas permanecem visíveis para transparência, mas não entram nas métricas. Resultados de avaliação preservam módulo e tópico de origem.</div>
    {atividades.length === 0 ? <section className="cartao" style={{ marginTop: 24 }}><h2>Sem atividades ainda</h2><p className="rotulo">Abra um material no módulo para iniciar seu primeiro registro.</p></section> : <section className="tabela-responsiva cartao" style={{ marginTop: 24 }}><table><caption>Suas sessões e avaliações, da mais recente para a mais antiga.</caption><thead><tr><th scope="col">Data</th><th scope="col">Tipo</th><th scope="col">Módulo e tópico</th><th scope="col">Contexto</th><th scope="col">Resultado</th></tr></thead><tbody>{atividades.map((atividade) => atividade.tipo === "SESSAO" ? <tr key={`sessao-${atividade.id}`}><td>{formatarData(atividade.ocorridaEm)}</td><td>Sessão</td><td>{atividade.sessao.modulo.titulo}<br /><span className="rotulo">{atividade.sessao.topico.nome}</span></td><td>{atividade.sessao.recurso.titulo}<br /><span className="rotulo">{formatarFormato(atividade.sessao.recurso.formato)} · {formatarMetodoEstudo(atividade.sessao.metodo)}{atividade.sessao.desafio ? ` · Desafio: ${atividade.sessao.desafio.meta}` : ""}</span></td><td>{atividade.sessao.duracaoMinutos ?? "—"} min · <span className="selo">{atividade.sessao.situacao.toLowerCase()}</span><br /><span className="rotulo">Dificuldade {atividade.sessao.dificuldadePercebida ?? "—"}/5 · Compreensão {atividade.sessao.compreensaoPercebida ?? "—"}/5</span></td></tr> : <tr key={`tentativa-${atividade.id}`}><td>{formatarData(atividade.ocorridaEm)}</td><td>Avaliação</td><td>{atividade.tentativa.modulo.titulo}<br /><span className="rotulo">{atividade.tentativa.topico.nome}</span></td><td>{atividade.tentativa.avaliacao.titulo}<br /><span className="rotulo">Tentativa {atividade.tentativa.numeroTentativa}</span></td><td>{formatarPorcentagem(atividade.tentativa.notaNormalizada)} · {atividade.tentativa.respostasCorretas}/{atividade.tentativa.totalQuestoes} acertos</td></tr>)}</tbody></table></section>}
  </main></EstruturaAutenticada>;
}
